GET http://localhost:3001/api/persons
Content-Type: text/html

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Pablo",
    "phone": "+593-0999-844118"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Adriana",
    "phone": "+593-0989-768444"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jorge",
    "phone": "+593-0954-213578"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "phone": "+593-0954-213578"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jorge",
    "phone": "+593-0985325481"
}